services:
  auth-server:
    build: .
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: your-production-secret-key-here
      JWT_SECRET_KEY: your-production-jwt-secret-here
      DATABASE_URL: "sqlite:///:memory:"
      DEFAULT_USERNAME: admin
      DEFAULT_EMAIL: admin@example.com
      DEFAULT_PASSWORD: admin123
    restart: unless-stopped